u-boot: enable CONFIG_SPL_MTD to fix undefined reference build error
Issue: LINUXEXEC-33873

Following SDK patch c922386ac04c ("HSD #15016518538: configs:
socfpga: Enable SPL_MTD config"), enable CONFIG_SPL_MTD for
Agilex nand defconfig to fix below build error:

include/nand.h:49:(.text.check_skip_len.constprop.0+0x90): undefined reference to `mtd_block_isbad'
include/nand.h:38:(.text.nand_read_skip_bad+0x148): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `mtd_read'

Signed-off-by: Liwei Song <liwei.song@windriver.com>