intel-socfpga/u-boot-socfpga: adjust patch context to fix do_patch error
Issue: LIN1023-2718

Adjust patch context to avoid below do_patch error caused by the updates
of u-boot-socfpga in SDK:

ERROR: u-boot-socfpga-1_v2023.04+gitAUTOINC+d2d95a62e3-r0 do_patch: QA Issue: Fuzz detected:
Applying patch 0001-drivers-watchdog-restore-watchdog-default-timeout-va.patch
patching file drivers/watchdog/Kconfig
Hunk #1 succeeded at 28 with fuzz 2 (offset 1 line).

Signed-off-by: Liwei Song <liwei.song@windriver.com>